excluded:
   - Pods
   - SampleApp/Pods
   - Core/APILayer/Tests
   - Core/APIUtilities
   - GraphQL/API

identifier_name:
  excluded:
    - id
  
inclusive_language:
  override_allowed_terms: ['ticketmaster']

line_length:
    warning: 200
    ignores_comments: true
