platform :ios, '12.1'
inhibit_all_warnings!

target 'DummyProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DummyProject
  pod 'RealifeTech-SDK', :path => '..'

end
